import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import TopMenuButton from "./components/common/TopMenuButton";
import ProgressBar from "./components/common/ProgressBar";
import AuthProvider from "./context/AuthProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "My Portfoliosite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${poppins.className}`}>
        <AuthProvider>
          <ProgressBar />
          <Header />
          {children}
          <TopMenuButton />
        </AuthProvider>
      </body>
    </html>
  );
}
