import type { Metadata } from "next";
import { M_PLUS_1 } from "next/font/google";
import "./globals.css";
import ContextProvider from "./context/ContextProvider";
import ProgressBar from "./components/common/ProgressBar";
import TopMenuButton from "./components/common/TopMenuButton";

const m_plus_1 = M_PLUS_1({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "My Portfoliosite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ja">
      <body className={`${m_plus_1.className} bg-slate-50 dark:bg-gray-800 dark:text-white`}>
        <ContextProvider>
          <ProgressBar />
          {children}
          <TopMenuButton />
        </ContextProvider>
      </body>
    </html>
  );
}
